runtime: java
env: flex
#service: customer
#runtime_config:  # Optional
#  jdk: openjdk8

handlers:
- url: /.*
  script: this field is required, but ignored
#env_variables:
#  'DBG_ENABLE': 'true'
manual_scaling:
    instances: 1

health_check:
  enable_health_check: False
